version: "3"

services:
  genesis:
    hostname: genesis
    image: ethereum/client-go
    volumes:
      - ./:/proyecto
    command: --datadir /proyecto/data init /proyecto/genesis.json

  geth:
    hostname: geth
    image: ethereum/client-go
    expose:
      - 3000
      - 8543
      - 8545
      - 8546
      - 8547
      - 30303
      - 30303/udp
    ports:
      - 3000:3000
      - 8543:8543
      - 8545:8545
      - 8546:8546
      - 8547:8547
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - //:/proyecto
    command: --port 3000 --nousb --networkid 58343 --nodiscover --datadir=/proyecto/data --maxpeers=0  --rpc --rpcport 8543 --rpcaddr 127.0.0.1 --rpccorsdomain "*" --rpcapi "eth,net,web3,personal,miner" --syncmode full --gcmode=archive
    depends_on:
      - genesis
